// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uzadgqyhepghdhatygch.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV6YWRncXloZXBnaGRoYXR5Z2NoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2NDgzOTcsImV4cCI6MjA1OTIyNDM5N30.DusCfVs1y7wG2uxGkSXuzbtTq50lLyU3AUx8YbvpBns";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);