
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uzadgqyhepghdhatygch.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV6YWRncXloZXBnaGRoYXR5Z2NoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2NDgzOTcsImV4cCI6MjA1OTIyNDM5N30.DusCfVs1y7wG2uxGkSXuzbtTq50lLyU3AUx8YbvpBns";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Helper function to set the current user for audit logs
export const setCurrentUserForAudit = async (userName: string) => {
  try {
    await supabase.rpc('set_app_user', { user_name: userName });
    return true;
  } catch (error) {
    console.error('Error setting current user for audit:', error);
    return false;
  }
};

// Reset the current user
export const resetCurrentUserForAudit = async () => {
  try {
    await supabase.rpc('reset_app_user');
    return true;
  } catch (error) {
    console.error('Error resetting current user for audit:', error);
    return false;
  }
};
